name: test workflow

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Test Work schedule
        run: echo "This step should run at 3 am UTC time"
   
